from scraper.scrape import scrape

urls = [
    'http://abcnews.go.com/',
    'http://www.cnn.com/',
    'http://www.nbcnews.com/',
    'http://www.huffingtonpost.com/',
    'http://www.cbsnews.com/',
    'http://www.usatoday.com/',
    'http://www.buzzfeed.com/',
    'http://www.nytimes.com/',
    'http://www.foxnews.com/',
    'http://www.dailymail.co.uk/ushome/index.html',
    'http://www.washingtonpost.com/',
    'http://bleacherreport.com/',
    'http://www.businessinsider.com/',
    'http://elitedaily.com/',
    'http://www.bbc.com/',
    'http://www.cnet.com/',
    'http://www.theguardian.com/us',
    'http://www.msn.com/en-us/news',
    'http://www.npr.org/',
    'http://www.nydailynews.com/',
    'http://www.latimes.com/',
    'http://nypost.com/',
    'http://time.com/',
    'http://mashable.com/',
    'http://www.sfgate.com/',
    'http://www.slate.com/',
    'http://www.upworthy.com/',
    'http://www.theblaze.com/',
    'http://www.telegraph.co.uk/',
    'http://www.usnews.com/',
    'http://www.vice.com/en_us',
    'http://www.chron.com/',
    'http://gawker.com/',
    'http://www.examiner.com/',
    'http://www.vox.com/',
    'http://www.chicagotribune.com/',
    'http://www.thedailybeast.com/',
    'http://www.salon.com/',
    'http://mic.com/',
    'http://www.mirror.co.uk/news/',
    'http://www.nj.com',
    'http://www.independent.co.uk/',
    'http://www.freep.com/',
    'http://www.bostonglobe.com/',
    'http://www.theatlantic.com/',
    'http://www.mlive.com/',
    'http://www.engadget.com/',
    'http://techcrunch.com/',
    'http://www.boston.com',
    'http://www.al.com/',
    'http://www.dallasnews.com/',
]

"""
Scrape the news articles
"""
scrape(urls, 'health')