name: "Generate Articles"
on:
    push:
jobs:
    generate-articles:
        runs-on: ubuntu-latest
        if: "contains(github.event.head_commit.message, 'Generate Articles')"
        steps:
            -   uses: actions/checkout@v2
                with:
                    submodules: true
            -   name: "Install setup tools"
                run: "python3 -m pip install -U pip setuptools"
            -   name: "Install Requirements"
                run: "python3 -m pip install -r ./scraper/requirements.txt"
            -   name: "Run Article Generator"
                run: "python3 ./main.py"
            -   name: "Stage Files"
                run: "git add -f ."
            -   name: "Commit files"
                run: |
                    git fetch --unshallow origin
                    git config --local user.email "actions@github.com"
                    git config --local user.name "GitHub Actions"
                    git commit -m "Generate Articles"
            -   name: Publish
                run: |-
                    git push -f